// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Sujitnapa21/app/ent/adult"
	"github.com/Sujitnapa21/app/ent/books"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// AdultCreate is the builder for creating a Adult entity.
type AdultCreate struct {
	config
	mutation *AdultMutation
	hooks    []Hook
}

// SetAmount sets the Amount field.
func (ac *AdultCreate) SetAmount(i int) *AdultCreate {
	ac.mutation.SetAmount(i)
	return ac
}

// AddBookIDs adds the books edge to Books by ids.
func (ac *AdultCreate) AddBookIDs(ids ...int) *AdultCreate {
	ac.mutation.AddBookIDs(ids...)
	return ac
}

// AddBooks adds the books edges to Books.
func (ac *AdultCreate) AddBooks(b ...*Books) *AdultCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return ac.AddBookIDs(ids...)
}

// Mutation returns the AdultMutation object of the builder.
func (ac *AdultCreate) Mutation() *AdultMutation {
	return ac.mutation
}

// Save creates the Adult in the database.
func (ac *AdultCreate) Save(ctx context.Context) (*Adult, error) {
	if _, ok := ac.mutation.Amount(); !ok {
		return nil, &ValidationError{Name: "Amount", err: errors.New("ent: missing required field \"Amount\"")}
	}
	var (
		err  error
		node *Adult
	)
	if len(ac.hooks) == 0 {
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdultMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ac.mutation = mutation
			node, err = ac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AdultCreate) SaveX(ctx context.Context) *Adult {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ac *AdultCreate) sqlSave(ctx context.Context) (*Adult, error) {
	a, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	a.ID = int(id)
	return a, nil
}

func (ac *AdultCreate) createSpec() (*Adult, *sqlgraph.CreateSpec) {
	var (
		a     = &Adult{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: adult.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: adult.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: adult.FieldAmount,
		})
		a.Amount = value
	}
	if nodes := ac.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adult.BooksTable,
			Columns: []string{adult.BooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: books.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return a, _spec
}
