// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Sujitnapa21/app/ent/kid"
	"github.com/Sujitnapa21/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// KidDelete is the builder for deleting a Kid entity.
type KidDelete struct {
	config
	hooks      []Hook
	mutation   *KidMutation
	predicates []predicate.Kid
}

// Where adds a new predicate to the delete builder.
func (kd *KidDelete) Where(ps ...predicate.Kid) *KidDelete {
	kd.predicates = append(kd.predicates, ps...)
	return kd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (kd *KidDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(kd.hooks) == 0 {
		affected, err = kd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*KidMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			kd.mutation = mutation
			affected, err = kd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(kd.hooks) - 1; i >= 0; i-- {
			mut = kd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, kd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (kd *KidDelete) ExecX(ctx context.Context) int {
	n, err := kd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (kd *KidDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: kid.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: kid.FieldID,
			},
		},
	}
	if ps := kd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, kd.driver, _spec)
}

// KidDeleteOne is the builder for deleting a single Kid entity.
type KidDeleteOne struct {
	kd *KidDelete
}

// Exec executes the deletion query.
func (kdo *KidDeleteOne) Exec(ctx context.Context) error {
	n, err := kdo.kd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{kid.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (kdo *KidDeleteOne) ExecX(ctx context.Context) {
	kdo.kd.ExecX(ctx)
}
