// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Books is the predicate function for books builders.
type Books func(*sql.Selector)

// Checkout is the predicate function for checkout builders.
type Checkout func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)
