// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Problem is the predicate function for problem builders.
type Problem func(*sql.Selector)

// Problemtype is the predicate function for problemtype builders.
type Problemtype func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)
