// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/tee16/app/ent/problem"
	"github.com/tee16/app/ent/problemtype"
)

// ProblemtypeCreate is the builder for creating a Problemtype entity.
type ProblemtypeCreate struct {
	config
	mutation *ProblemtypeMutation
	hooks    []Hook
}

// SetPROBLEMTYPE sets the PROBLEMTYPE field.
func (pc *ProblemtypeCreate) SetPROBLEMTYPE(s string) *ProblemtypeCreate {
	pc.mutation.SetPROBLEMTYPE(s)
	return pc
}

// AddProblemIDs adds the Problem edge to Problem by ids.
func (pc *ProblemtypeCreate) AddProblemIDs(ids ...int) *ProblemtypeCreate {
	pc.mutation.AddProblemIDs(ids...)
	return pc
}

// AddProblem adds the Problem edges to Problem.
func (pc *ProblemtypeCreate) AddProblem(p ...*Problem) *ProblemtypeCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pc.AddProblemIDs(ids...)
}

// Mutation returns the ProblemtypeMutation object of the builder.
func (pc *ProblemtypeCreate) Mutation() *ProblemtypeMutation {
	return pc.mutation
}

// Save creates the Problemtype in the database.
func (pc *ProblemtypeCreate) Save(ctx context.Context) (*Problemtype, error) {
	if _, ok := pc.mutation.PROBLEMTYPE(); !ok {
		return nil, &ValidationError{Name: "PROBLEMTYPE", err: errors.New("ent: missing required field \"PROBLEMTYPE\"")}
	}
	var (
		err  error
		node *Problemtype
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProblemtypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProblemtypeCreate) SaveX(ctx context.Context) *Problemtype {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *ProblemtypeCreate) sqlSave(ctx context.Context) (*Problemtype, error) {
	pr, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pr.ID = int(id)
	return pr, nil
}

func (pc *ProblemtypeCreate) createSpec() (*Problemtype, *sqlgraph.CreateSpec) {
	var (
		pr    = &Problemtype{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: problemtype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: problemtype.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.PROBLEMTYPE(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: problemtype.FieldPROBLEMTYPE,
		})
		pr.PROBLEMTYPE = value
	}
	if nodes := pc.mutation.ProblemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problemtype.ProblemTable,
			Columns: []string{problemtype.ProblemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: problem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pr, _spec
}
