// Code generated by entc, DO NOT EDIT.

package checkout

import (
	"time"

	"github.com/chanudomsr/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CHECKOUTDATE applies equality check predicate on the "CHECKOUTDATE" field. It's identical to CHECKOUTDATEEQ.
func CHECKOUTDATE(v time.Time) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCHECKOUTDATE), v))
	})
}

// CHECKOUTDATEEQ applies the EQ predicate on the "CHECKOUTDATE" field.
func CHECKOUTDATEEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCHECKOUTDATE), v))
	})
}

// CHECKOUTDATENEQ applies the NEQ predicate on the "CHECKOUTDATE" field.
func CHECKOUTDATENEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCHECKOUTDATE), v))
	})
}

// CHECKOUTDATEIn applies the In predicate on the "CHECKOUTDATE" field.
func CHECKOUTDATEIn(vs ...time.Time) predicate.Checkout {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Checkout(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCHECKOUTDATE), v...))
	})
}

// CHECKOUTDATENotIn applies the NotIn predicate on the "CHECKOUTDATE" field.
func CHECKOUTDATENotIn(vs ...time.Time) predicate.Checkout {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Checkout(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCHECKOUTDATE), v...))
	})
}

// CHECKOUTDATEGT applies the GT predicate on the "CHECKOUTDATE" field.
func CHECKOUTDATEGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCHECKOUTDATE), v))
	})
}

// CHECKOUTDATEGTE applies the GTE predicate on the "CHECKOUTDATE" field.
func CHECKOUTDATEGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCHECKOUTDATE), v))
	})
}

// CHECKOUTDATELT applies the LT predicate on the "CHECKOUTDATE" field.
func CHECKOUTDATELT(v time.Time) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCHECKOUTDATE), v))
	})
}

// CHECKOUTDATELTE applies the LTE predicate on the "CHECKOUTDATE" field.
func CHECKOUTDATELTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCHECKOUTDATE), v))
	})
}

// HasBooks applies the HasEdge predicate on the "books" edge.
func HasBooks() predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BooksTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, BooksTable, BooksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBooksWith applies the HasEdge predicate on the "books" edge with a given conditions (other predicates).
func HasBooksWith(preds ...predicate.Books) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BooksInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, BooksTable, BooksColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CustomerTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CustomerInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEmployee applies the HasEdge predicate on the "employee" edge.
func HasEmployee() predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EmployeeTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeeWith applies the HasEdge predicate on the "employee" edge with a given conditions (other predicates).
func HasEmployeeWith(preds ...predicate.Employee) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EmployeeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoom applies the HasEdge predicate on the "room" edge.
func HasRoom() predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, RoomTable, RoomColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoomWith applies the HasEdge predicate on the "room" edge with a given conditions (other predicates).
func HasRoomWith(preds ...predicate.Room) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, RoomTable, RoomColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Checkout) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Checkout) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Checkout) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		p(s.Not())
	})
}
