// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/ADMIN/app/ent/customer"
	"github.com/ADMIN/app/ent/customertype"
	"github.com/ADMIN/app/ent/gender"
	"github.com/ADMIN/app/ent/predicate"
	"github.com/ADMIN/app/ent/title"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// CustomerUpdate is the builder for updating Customer entities.
type CustomerUpdate struct {
	config
	hooks      []Hook
	mutation   *CustomerMutation
	predicates []predicate.Customer
}

// Where adds a new predicate for the builder.
func (cu *CustomerUpdate) Where(ps ...predicate.Customer) *CustomerUpdate {
	cu.predicates = append(cu.predicates, ps...)
	return cu
}

// SetNAME sets the NAME field.
func (cu *CustomerUpdate) SetNAME(s string) *CustomerUpdate {
	cu.mutation.SetNAME(s)
	return cu
}

// SetAGE sets the AGE field.
func (cu *CustomerUpdate) SetAGE(i int) *CustomerUpdate {
	cu.mutation.ResetAGE()
	cu.mutation.SetAGE(i)
	return cu
}

// AddAGE adds i to AGE.
func (cu *CustomerUpdate) AddAGE(i int) *CustomerUpdate {
	cu.mutation.AddAGE(i)
	return cu
}

// SetEMAIL sets the EMAIL field.
func (cu *CustomerUpdate) SetEMAIL(s string) *CustomerUpdate {
	cu.mutation.SetEMAIL(s)
	return cu
}

// SetUSERNAME sets the USERNAME field.
func (cu *CustomerUpdate) SetUSERNAME(s string) *CustomerUpdate {
	cu.mutation.SetUSERNAME(s)
	return cu
}

// SetPASSWORD sets the PASSWORD field.
func (cu *CustomerUpdate) SetPASSWORD(s string) *CustomerUpdate {
	cu.mutation.SetPASSWORD(s)
	return cu
}

// SetGenderID sets the gender edge to Gender by id.
func (cu *CustomerUpdate) SetGenderID(id int) *CustomerUpdate {
	cu.mutation.SetGenderID(id)
	return cu
}

// SetNillableGenderID sets the gender edge to Gender by id if the given value is not nil.
func (cu *CustomerUpdate) SetNillableGenderID(id *int) *CustomerUpdate {
	if id != nil {
		cu = cu.SetGenderID(*id)
	}
	return cu
}

// SetGender sets the gender edge to Gender.
func (cu *CustomerUpdate) SetGender(g *Gender) *CustomerUpdate {
	return cu.SetGenderID(g.ID)
}

// SetCustomertypeID sets the customertype edge to Customertype by id.
func (cu *CustomerUpdate) SetCustomertypeID(id int) *CustomerUpdate {
	cu.mutation.SetCustomertypeID(id)
	return cu
}

// SetNillableCustomertypeID sets the customertype edge to Customertype by id if the given value is not nil.
func (cu *CustomerUpdate) SetNillableCustomertypeID(id *int) *CustomerUpdate {
	if id != nil {
		cu = cu.SetCustomertypeID(*id)
	}
	return cu
}

// SetCustomertype sets the customertype edge to Customertype.
func (cu *CustomerUpdate) SetCustomertype(c *Customertype) *CustomerUpdate {
	return cu.SetCustomertypeID(c.ID)
}

// SetTitleID sets the title edge to Title by id.
func (cu *CustomerUpdate) SetTitleID(id int) *CustomerUpdate {
	cu.mutation.SetTitleID(id)
	return cu
}

// SetNillableTitleID sets the title edge to Title by id if the given value is not nil.
func (cu *CustomerUpdate) SetNillableTitleID(id *int) *CustomerUpdate {
	if id != nil {
		cu = cu.SetTitleID(*id)
	}
	return cu
}

// SetTitle sets the title edge to Title.
func (cu *CustomerUpdate) SetTitle(t *Title) *CustomerUpdate {
	return cu.SetTitleID(t.ID)
}

// Mutation returns the CustomerMutation object of the builder.
func (cu *CustomerUpdate) Mutation() *CustomerMutation {
	return cu.mutation
}

// ClearGender clears the gender edge to Gender.
func (cu *CustomerUpdate) ClearGender() *CustomerUpdate {
	cu.mutation.ClearGender()
	return cu
}

// ClearCustomertype clears the customertype edge to Customertype.
func (cu *CustomerUpdate) ClearCustomertype() *CustomerUpdate {
	cu.mutation.ClearCustomertype()
	return cu
}

// ClearTitle clears the title edge to Title.
func (cu *CustomerUpdate) ClearTitle() *CustomerUpdate {
	cu.mutation.ClearTitle()
	return cu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *CustomerUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := cu.mutation.EMAIL(); ok {
		if err := customer.EMAILValidator(v); err != nil {
			return 0, &ValidationError{Name: "EMAIL", err: fmt.Errorf("ent: validator failed for field \"EMAIL\": %w", err)}
		}
	}
	if v, ok := cu.mutation.USERNAME(); ok {
		if err := customer.USERNAMEValidator(v); err != nil {
			return 0, &ValidationError{Name: "USERNAME", err: fmt.Errorf("ent: validator failed for field \"USERNAME\": %w", err)}
		}
	}
	if v, ok := cu.mutation.PASSWORD(); ok {
		if err := customer.PASSWORDValidator(v); err != nil {
			return 0, &ValidationError{Name: "PASSWORD", err: fmt.Errorf("ent: validator failed for field \"PASSWORD\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CustomerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CustomerUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CustomerUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CustomerUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CustomerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   customer.Table,
			Columns: customer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: customer.FieldID,
			},
		},
	}
	if ps := cu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.NAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: customer.FieldNAME,
		})
	}
	if value, ok := cu.mutation.AGE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: customer.FieldAGE,
		})
	}
	if value, ok := cu.mutation.AddedAGE(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: customer.FieldAGE,
		})
	}
	if value, ok := cu.mutation.EMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: customer.FieldEMAIL,
		})
	}
	if value, ok := cu.mutation.USERNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: customer.FieldUSERNAME,
		})
	}
	if value, ok := cu.mutation.PASSWORD(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: customer.FieldPASSWORD,
		})
	}
	if cu.mutation.GenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.GenderTable,
			Columns: []string{customer.GenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.GenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.GenderTable,
			Columns: []string{customer.GenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.CustomertypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.CustomertypeTable,
			Columns: []string{customer.CustomertypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: customertype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.CustomertypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.CustomertypeTable,
			Columns: []string{customer.CustomertypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: customertype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.TitleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.TitleTable,
			Columns: []string{customer.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: title.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.TitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.TitleTable,
			Columns: []string{customer.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: title.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customer.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// CustomerUpdateOne is the builder for updating a single Customer entity.
type CustomerUpdateOne struct {
	config
	hooks    []Hook
	mutation *CustomerMutation
}

// SetNAME sets the NAME field.
func (cuo *CustomerUpdateOne) SetNAME(s string) *CustomerUpdateOne {
	cuo.mutation.SetNAME(s)
	return cuo
}

// SetAGE sets the AGE field.
func (cuo *CustomerUpdateOne) SetAGE(i int) *CustomerUpdateOne {
	cuo.mutation.ResetAGE()
	cuo.mutation.SetAGE(i)
	return cuo
}

// AddAGE adds i to AGE.
func (cuo *CustomerUpdateOne) AddAGE(i int) *CustomerUpdateOne {
	cuo.mutation.AddAGE(i)
	return cuo
}

// SetEMAIL sets the EMAIL field.
func (cuo *CustomerUpdateOne) SetEMAIL(s string) *CustomerUpdateOne {
	cuo.mutation.SetEMAIL(s)
	return cuo
}

// SetUSERNAME sets the USERNAME field.
func (cuo *CustomerUpdateOne) SetUSERNAME(s string) *CustomerUpdateOne {
	cuo.mutation.SetUSERNAME(s)
	return cuo
}

// SetPASSWORD sets the PASSWORD field.
func (cuo *CustomerUpdateOne) SetPASSWORD(s string) *CustomerUpdateOne {
	cuo.mutation.SetPASSWORD(s)
	return cuo
}

// SetGenderID sets the gender edge to Gender by id.
func (cuo *CustomerUpdateOne) SetGenderID(id int) *CustomerUpdateOne {
	cuo.mutation.SetGenderID(id)
	return cuo
}

// SetNillableGenderID sets the gender edge to Gender by id if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableGenderID(id *int) *CustomerUpdateOne {
	if id != nil {
		cuo = cuo.SetGenderID(*id)
	}
	return cuo
}

// SetGender sets the gender edge to Gender.
func (cuo *CustomerUpdateOne) SetGender(g *Gender) *CustomerUpdateOne {
	return cuo.SetGenderID(g.ID)
}

// SetCustomertypeID sets the customertype edge to Customertype by id.
func (cuo *CustomerUpdateOne) SetCustomertypeID(id int) *CustomerUpdateOne {
	cuo.mutation.SetCustomertypeID(id)
	return cuo
}

// SetNillableCustomertypeID sets the customertype edge to Customertype by id if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableCustomertypeID(id *int) *CustomerUpdateOne {
	if id != nil {
		cuo = cuo.SetCustomertypeID(*id)
	}
	return cuo
}

// SetCustomertype sets the customertype edge to Customertype.
func (cuo *CustomerUpdateOne) SetCustomertype(c *Customertype) *CustomerUpdateOne {
	return cuo.SetCustomertypeID(c.ID)
}

// SetTitleID sets the title edge to Title by id.
func (cuo *CustomerUpdateOne) SetTitleID(id int) *CustomerUpdateOne {
	cuo.mutation.SetTitleID(id)
	return cuo
}

// SetNillableTitleID sets the title edge to Title by id if the given value is not nil.
func (cuo *CustomerUpdateOne) SetNillableTitleID(id *int) *CustomerUpdateOne {
	if id != nil {
		cuo = cuo.SetTitleID(*id)
	}
	return cuo
}

// SetTitle sets the title edge to Title.
func (cuo *CustomerUpdateOne) SetTitle(t *Title) *CustomerUpdateOne {
	return cuo.SetTitleID(t.ID)
}

// Mutation returns the CustomerMutation object of the builder.
func (cuo *CustomerUpdateOne) Mutation() *CustomerMutation {
	return cuo.mutation
}

// ClearGender clears the gender edge to Gender.
func (cuo *CustomerUpdateOne) ClearGender() *CustomerUpdateOne {
	cuo.mutation.ClearGender()
	return cuo
}

// ClearCustomertype clears the customertype edge to Customertype.
func (cuo *CustomerUpdateOne) ClearCustomertype() *CustomerUpdateOne {
	cuo.mutation.ClearCustomertype()
	return cuo
}

// ClearTitle clears the title edge to Title.
func (cuo *CustomerUpdateOne) ClearTitle() *CustomerUpdateOne {
	cuo.mutation.ClearTitle()
	return cuo
}

// Save executes the query and returns the updated entity.
func (cuo *CustomerUpdateOne) Save(ctx context.Context) (*Customer, error) {
	if v, ok := cuo.mutation.EMAIL(); ok {
		if err := customer.EMAILValidator(v); err != nil {
			return nil, &ValidationError{Name: "EMAIL", err: fmt.Errorf("ent: validator failed for field \"EMAIL\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.USERNAME(); ok {
		if err := customer.USERNAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "USERNAME", err: fmt.Errorf("ent: validator failed for field \"USERNAME\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.PASSWORD(); ok {
		if err := customer.PASSWORDValidator(v); err != nil {
			return nil, &ValidationError{Name: "PASSWORD", err: fmt.Errorf("ent: validator failed for field \"PASSWORD\": %w", err)}
		}
	}

	var (
		err  error
		node *Customer
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CustomerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CustomerUpdateOne) SaveX(ctx context.Context) *Customer {
	c, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return c
}

// Exec executes the query on the entity.
func (cuo *CustomerUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CustomerUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CustomerUpdateOne) sqlSave(ctx context.Context) (c *Customer, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   customer.Table,
			Columns: customer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: customer.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Customer.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cuo.mutation.NAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: customer.FieldNAME,
		})
	}
	if value, ok := cuo.mutation.AGE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: customer.FieldAGE,
		})
	}
	if value, ok := cuo.mutation.AddedAGE(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: customer.FieldAGE,
		})
	}
	if value, ok := cuo.mutation.EMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: customer.FieldEMAIL,
		})
	}
	if value, ok := cuo.mutation.USERNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: customer.FieldUSERNAME,
		})
	}
	if value, ok := cuo.mutation.PASSWORD(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: customer.FieldPASSWORD,
		})
	}
	if cuo.mutation.GenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.GenderTable,
			Columns: []string{customer.GenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.GenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.GenderTable,
			Columns: []string{customer.GenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.CustomertypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.CustomertypeTable,
			Columns: []string{customer.CustomertypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: customertype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.CustomertypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.CustomertypeTable,
			Columns: []string{customer.CustomertypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: customertype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.TitleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.TitleTable,
			Columns: []string{customer.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: title.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.TitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.TitleTable,
			Columns: []string{customer.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: title.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	c = &Customer{config: cuo.config}
	_spec.Assign = c.assignValues
	_spec.ScanValues = c.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customer.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return c, nil
}
