/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntAdult,
    EntAdultFromJSON,
    EntAdultFromJSONTyped,
    EntAdultToJSON,
    EntCustomer,
    EntCustomerFromJSON,
    EntCustomerFromJSONTyped,
    EntCustomerToJSON,
    EntKid,
    EntKidFromJSON,
    EntKidFromJSONTyped,
    EntKidToJSON,
    EntRoom,
    EntRoomFromJSON,
    EntRoomFromJSONTyped,
    EntRoomToJSON,
    EntRoomamount,
    EntRoomamountFromJSON,
    EntRoomamountFromJSONTyped,
    EntRoomamountToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBooksEdges
 */
export interface EntBooksEdges {
    /**
     * 
     * @type {EntAdult}
     * @memberof EntBooksEdges
     */
    adult?: EntAdult;
    /**
     * 
     * @type {EntCustomer}
     * @memberof EntBooksEdges
     */
    customer?: EntCustomer;
    /**
     * 
     * @type {EntKid}
     * @memberof EntBooksEdges
     */
    kid?: EntKid;
    /**
     * 
     * @type {EntRoom}
     * @memberof EntBooksEdges
     */
    room?: EntRoom;
    /**
     * 
     * @type {EntRoomamount}
     * @memberof EntBooksEdges
     */
    roomamount?: EntRoomamount;
}

export function EntBooksEdgesFromJSON(json: any): EntBooksEdges {
    return EntBooksEdgesFromJSONTyped(json, false);
}

export function EntBooksEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBooksEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'adult': !exists(json, 'adult') ? undefined : EntAdultFromJSON(json['adult']),
        'customer': !exists(json, 'customer') ? undefined : EntCustomerFromJSON(json['customer']),
        'kid': !exists(json, 'kid') ? undefined : EntKidFromJSON(json['kid']),
        'room': !exists(json, 'room') ? undefined : EntRoomFromJSON(json['room']),
        'roomamount': !exists(json, 'roomamount') ? undefined : EntRoomamountFromJSON(json['roomamount']),
    };
}

export function EntBooksEdgesToJSON(value?: EntBooksEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'adult': EntAdultToJSON(value.adult),
        'customer': EntCustomerToJSON(value.customer),
        'kid': EntKidToJSON(value.kid),
        'room': EntRoomToJSON(value.room),
        'roomamount': EntRoomamountToJSON(value.roomamount),
    };
}


