/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBooksEdges,
    EntBooksEdgesFromJSON,
    EntBooksEdgesFromJSONTyped,
    EntBooksEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBooks
 */
export interface EntBooks {
    /**
     * Checkin holds the value of the "Checkin" field.
     * @type {string}
     * @memberof EntBooks
     */
    checkin?: string;
    /**
     * Checkout holds the value of the "Checkout" field.
     * @type {string}
     * @memberof EntBooks
     */
    checkout?: string;
    /**
     * 
     * @type {EntBooksEdges}
     * @memberof EntBooks
     */
    edges?: EntBooksEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBooks
     */
    id?: number;
}

export function EntBooksFromJSON(json: any): EntBooks {
    return EntBooksFromJSONTyped(json, false);
}

export function EntBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBooks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkin': !exists(json, 'Checkin') ? undefined : json['Checkin'],
        'checkout': !exists(json, 'Checkout') ? undefined : json['Checkout'],
        'edges': !exists(json, 'edges') ? undefined : EntBooksEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntBooksToJSON(value?: EntBooks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Checkin': value.checkin,
        'Checkout': value.checkout,
        'edges': EntBooksEdgesToJSON(value.edges),
        'id': value.id,
    };
}


