/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoomamountEdges,
    EntRoomamountEdgesFromJSON,
    EntRoomamountEdgesFromJSONTyped,
    EntRoomamountEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomamount
 */
export interface EntRoomamount {
    /**
     * Amount holds the value of the "Amount" field.
     * @type {number}
     * @memberof EntRoomamount
     */
    amount?: number;
    /**
     * 
     * @type {EntRoomamountEdges}
     * @memberof EntRoomamount
     */
    edges?: EntRoomamountEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRoomamount
     */
    id?: number;
}

export function EntRoomamountFromJSON(json: any): EntRoomamount {
    return EntRoomamountFromJSONTyped(json, false);
}

export function EntRoomamountFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomamount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'Amount') ? undefined : json['Amount'],
        'edges': !exists(json, 'edges') ? undefined : EntRoomamountEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntRoomamountToJSON(value?: EntRoomamount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Amount': value.amount,
        'edges': EntRoomamountEdgesToJSON(value.edges),
        'id': value.id,
    };
}


