// Code generated by entc, DO NOT EDIT.

package roomstate

const (
	// Label holds the string label denoting the roomstate type in the database.
	Label = "roomstate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldROOMSTATE holds the string denoting the roomstate field in the database.
	FieldROOMSTATE = "roomstate"

	// EdgeRoom3 holds the string denoting the room3 edge name in mutations.
	EdgeRoom3 = "Room3"

	// Table holds the table name of the roomstate in the database.
	Table = "roomstates"
	// Room3Table is the table the holds the Room3 relation/edge.
	Room3Table = "rooms"
	// Room3InverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	Room3InverseTable = "rooms"
	// Room3Column is the table column denoting the Room3 relation/edge.
	Room3Column = "roomstate_room3"
)

// Columns holds all SQL columns for roomstate fields.
var Columns = []string{
	FieldID,
	FieldROOMSTATE,
}

var (
	// ROOMSTATEValidator is a validator for the "ROOMSTATE" field. It is called by the builders before save.
	ROOMSTATEValidator func(string) error
)
