// Code generated by entc, DO NOT EDIT.

package roomstate

import (
	"github.com/PBank/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// ROOMSTATE applies equality check predicate on the "ROOMSTATE" field. It's identical to ROOMSTATEEQ.
func ROOMSTATE(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATEEQ applies the EQ predicate on the "ROOMSTATE" field.
func ROOMSTATEEQ(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATENEQ applies the NEQ predicate on the "ROOMSTATE" field.
func ROOMSTATENEQ(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATEIn applies the In predicate on the "ROOMSTATE" field.
func ROOMSTATEIn(vs ...string) predicate.Roomstate {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Roomstate(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldROOMSTATE), v...))
	})
}

// ROOMSTATENotIn applies the NotIn predicate on the "ROOMSTATE" field.
func ROOMSTATENotIn(vs ...string) predicate.Roomstate {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Roomstate(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldROOMSTATE), v...))
	})
}

// ROOMSTATEGT applies the GT predicate on the "ROOMSTATE" field.
func ROOMSTATEGT(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATEGTE applies the GTE predicate on the "ROOMSTATE" field.
func ROOMSTATEGTE(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATELT applies the LT predicate on the "ROOMSTATE" field.
func ROOMSTATELT(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATELTE applies the LTE predicate on the "ROOMSTATE" field.
func ROOMSTATELTE(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATEContains applies the Contains predicate on the "ROOMSTATE" field.
func ROOMSTATEContains(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATEHasPrefix applies the HasPrefix predicate on the "ROOMSTATE" field.
func ROOMSTATEHasPrefix(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATEHasSuffix applies the HasSuffix predicate on the "ROOMSTATE" field.
func ROOMSTATEHasSuffix(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATEEqualFold applies the EqualFold predicate on the "ROOMSTATE" field.
func ROOMSTATEEqualFold(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldROOMSTATE), v))
	})
}

// ROOMSTATEContainsFold applies the ContainsFold predicate on the "ROOMSTATE" field.
func ROOMSTATEContainsFold(v string) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldROOMSTATE), v))
	})
}

// HasRoom3 applies the HasEdge predicate on the "Room3" edge.
func HasRoom3() predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(Room3Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, Room3Table, Room3Column),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoom3With applies the HasEdge predicate on the "Room3" edge with a given conditions (other predicates).
func HasRoom3With(preds ...predicate.Room) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(Room3InverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, Room3Table, Room3Column),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Roomstate) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Roomstate) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Roomstate) predicate.Roomstate {
	return predicate.Roomstate(func(s *sql.Selector) {
		p(s.Not())
	})
}
