/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCheckout,
    EntCheckoutFromJSON,
    EntCheckoutFromJSONTyped,
    EntCheckoutToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBooksEdges
 */
export interface EntBooksEdges {
    /**
     * 
     * @type {EntCheckout}
     * @memberof EntBooksEdges
     */
    checkout1?: EntCheckout;
}

export function EntBooksEdgesFromJSON(json: any): EntBooksEdges {
    return EntBooksEdgesFromJSONTyped(json, false);
}

export function EntBooksEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBooksEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkout1': !exists(json, 'checkout1') ? undefined : EntCheckoutFromJSON(json['checkout1']),
    };
}

export function EntBooksEdgesToJSON(value?: EntBooksEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checkout1': EntCheckoutToJSON(value.checkout1),
    };
}


