/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCheckoutEdges,
    EntCheckoutEdgesFromJSON,
    EntCheckoutEdgesFromJSONTyped,
    EntCheckoutEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCheckout
 */
export interface EntCheckout {
    /**
     * CHECKOUTDATE holds the value of the "CHECKOUTDATE" field.
     * @type {string}
     * @memberof EntCheckout
     */
    cHECKOUTDATE?: string;
    /**
     * 
     * @type {EntCheckoutEdges}
     * @memberof EntCheckout
     */
    edges?: EntCheckoutEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntCheckout
     */
    id?: number;
}

export function EntCheckoutFromJSON(json: any): EntCheckout {
    return EntCheckoutFromJSONTyped(json, false);
}

export function EntCheckoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCheckout {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cHECKOUTDATE': !exists(json, 'CHECKOUTDATE') ? undefined : json['CHECKOUTDATE'],
        'edges': !exists(json, 'edges') ? undefined : EntCheckoutEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntCheckoutToJSON(value?: EntCheckout | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CHECKOUTDATE': value.cHECKOUTDATE,
        'edges': EntCheckoutEdgesToJSON(value.edges),
        'id': value.id,
    };
}


