/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEmployeeEdges,
    EntEmployeeEdgesFromJSON,
    EntEmployeeEdgesFromJSONTyped,
    EntEmployeeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntEmployee
 */
export interface EntEmployee {
    /**
     * EMPLOYEENAME holds the value of the "EMPLOYEENAME" field.
     * @type {string}
     * @memberof EntEmployee
     */
    eMPLOYEENAME?: string;
    /**
     * EMPLOYEEPASSWORD holds the value of the "EMPLOYEEPASSWORD" field.
     * @type {string}
     * @memberof EntEmployee
     */
    eMPLOYEEPASSWORD?: string;
    /**
     * 
     * @type {EntEmployeeEdges}
     * @memberof EntEmployee
     */
    edges?: EntEmployeeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntEmployee
     */
    id?: number;
}

export function EntEmployeeFromJSON(json: any): EntEmployee {
    return EntEmployeeFromJSONTyped(json, false);
}

export function EntEmployeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntEmployee {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eMPLOYEENAME': !exists(json, 'EMPLOYEENAME') ? undefined : json['EMPLOYEENAME'],
        'eMPLOYEEPASSWORD': !exists(json, 'EMPLOYEEPASSWORD') ? undefined : json['EMPLOYEEPASSWORD'],
        'edges': !exists(json, 'edges') ? undefined : EntEmployeeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntEmployeeToJSON(value?: EntEmployee | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'EMPLOYEENAME': value.eMPLOYEENAME,
        'EMPLOYEEPASSWORD': value.eMPLOYEEPASSWORD,
        'edges': EntEmployeeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


