// Code generated by entc, DO NOT EDIT.

package room

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldROOMNUMBER holds the string denoting the roomnumber field in the database.
	FieldROOMNUMBER = "roomnumber"

	// EdgeRoomtype holds the string denoting the roomtype edge name in mutations.
	EdgeRoomtype = "Roomtype"
	// EdgePromotion holds the string denoting the promotion edge name in mutations.
	EdgePromotion = "Promotion"
	// EdgeRoomstate holds the string denoting the roomstate edge name in mutations.
	EdgeRoomstate = "roomstate"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// RoomtypeTable is the table the holds the Roomtype relation/edge.
	RoomtypeTable = "rooms"
	// RoomtypeInverseTable is the table name for the Roomtype entity.
	// It exists in this package in order to avoid circular dependency with the "roomtype" package.
	RoomtypeInverseTable = "roomtypes"
	// RoomtypeColumn is the table column denoting the Roomtype relation/edge.
	RoomtypeColumn = "roomtype_room1"
	// PromotionTable is the table the holds the Promotion relation/edge.
	PromotionTable = "rooms"
	// PromotionInverseTable is the table name for the Promotion entity.
	// It exists in this package in order to avoid circular dependency with the "promotion" package.
	PromotionInverseTable = "promotions"
	// PromotionColumn is the table column denoting the Promotion relation/edge.
	PromotionColumn = "promotion_room2"
	// RoomstateTable is the table the holds the roomstate relation/edge.
	RoomstateTable = "rooms"
	// RoomstateInverseTable is the table name for the Roomstate entity.
	// It exists in this package in order to avoid circular dependency with the "roomstate" package.
	RoomstateInverseTable = "roomstates"
	// RoomstateColumn is the table column denoting the roomstate relation/edge.
	RoomstateColumn = "roomstate_room3"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldROOMNUMBER,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Room type.
var ForeignKeys = []string{
	"promotion_room2",
	"roomstate_room3",
	"roomtype_room1",
}
