// Code generated by entc, DO NOT EDIT.

package room

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldROOMNUMBER holds the string denoting the roomnumber field in the database.
	FieldROOMNUMBER = "roomnumber"

	// EdgeCheckout4 holds the string denoting the checkout4 edge name in mutations.
	EdgeCheckout4 = "checkout4"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// Checkout4Table is the table the holds the checkout4 relation/edge.
	Checkout4Table = "checkouts"
	// Checkout4InverseTable is the table name for the Checkout entity.
	// It exists in this package in order to avoid circular dependency with the "checkout" package.
	Checkout4InverseTable = "checkouts"
	// Checkout4Column is the table column denoting the checkout4 relation/edge.
	Checkout4Column = "room_checkout4"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldROOMNUMBER,
}
