// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// CustomersColumns holds the columns for the "customers" table.
	CustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString, Unique: true},
		{Name: "customertype", Type: field.TypeInt, Nullable: true},
		{Name: "gender", Type: field.TypeInt, Nullable: true},
		{Name: "title", Type: field.TypeInt, Nullable: true},
	}
	// CustomersTable holds the schema information for the "customers" table.
	CustomersTable = &schema.Table{
		Name:       "customers",
		Columns:    CustomersColumns,
		PrimaryKey: []*schema.Column{CustomersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "customers_customertypes_customer3",
				Columns: []*schema.Column{CustomersColumns[6]},

				RefColumns: []*schema.Column{CustomertypesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "customers_genders_customer2",
				Columns: []*schema.Column{CustomersColumns[7]},

				RefColumns: []*schema.Column{GendersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "customers_titles_customer4",
				Columns: []*schema.Column{CustomersColumns[8]},

				RefColumns: []*schema.Column{TitlesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CustomertypesColumns holds the columns for the "customertypes" table.
	CustomertypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "customertype", Type: field.TypeString, Unique: true},
	}
	// CustomertypesTable holds the schema information for the "customertypes" table.
	CustomertypesTable = &schema.Table{
		Name:        "customertypes",
		Columns:     CustomertypesColumns,
		PrimaryKey:  []*schema.Column{CustomertypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// GendersColumns holds the columns for the "genders" table.
	GendersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gender", Type: field.TypeString, Unique: true},
	}
	// GendersTable holds the schema information for the "genders" table.
	GendersTable = &schema.Table{
		Name:        "genders",
		Columns:     GendersColumns,
		PrimaryKey:  []*schema.Column{GendersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// TitlesColumns holds the columns for the "titles" table.
	TitlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "titletype", Type: field.TypeString, Unique: true},
	}
	// TitlesTable holds the schema information for the "titles" table.
	TitlesTable = &schema.Table{
		Name:        "titles",
		Columns:     TitlesColumns,
		PrimaryKey:  []*schema.Column{TitlesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CustomersTable,
		CustomertypesTable,
		GendersTable,
		TitlesTable,
	}
)

func init() {
	CustomersTable.ForeignKeys[0].RefTable = CustomertypesTable
	CustomersTable.ForeignKeys[1].RefTable = GendersTable
	CustomersTable.ForeignKeys[2].RefTable = TitlesTable
}
