// Code generated by entc, DO NOT EDIT.

package adult

const (
	// Label holds the string label denoting the adult type in the database.
	Label = "adult"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"

	// EdgeBooks holds the string denoting the books edge name in mutations.
	EdgeBooks = "books"

	// Table holds the table name of the adult in the database.
	Table = "adults"
	// BooksTable is the table the holds the books relation/edge.
	BooksTable = "books"
	// BooksInverseTable is the table name for the Books entity.
	// It exists in this package in order to avoid circular dependency with the "books" package.
	BooksInverseTable = "books"
	// BooksColumn is the table column denoting the books relation/edge.
	BooksColumn = "adult_books"
)

// Columns holds all SQL columns for adult fields.
var Columns = []string{
	FieldID,
	FieldAmount,
}
