// Code generated by entc, DO NOT EDIT.

package problemtype

const (
	// Label holds the string label denoting the problemtype type in the database.
	Label = "problemtype"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPROBLEMTYPE holds the string denoting the problemtype field in the database.
	FieldPROBLEMTYPE = "problemtype"

	// EdgeProblem holds the string denoting the problem edge name in mutations.
	EdgeProblem = "Problem"

	// Table holds the table name of the problemtype in the database.
	Table = "problemtypes"
	// ProblemTable is the table the holds the Problem relation/edge.
	ProblemTable = "problems"
	// ProblemInverseTable is the table name for the Problem entity.
	// It exists in this package in order to avoid circular dependency with the "problem" package.
	ProblemInverseTable = "problems"
	// ProblemColumn is the table column denoting the Problem relation/edge.
	ProblemColumn = "problemtype_problem"
)

// Columns holds all SQL columns for problemtype fields.
var Columns = []string{
	FieldID,
	FieldPROBLEMTYPE,
}
