/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCustomer,
    EntCustomerFromJSON,
    EntCustomerFromJSONTyped,
    EntCustomerToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTitleEdges
 */
export interface EntTitleEdges {
    /**
     * Customer4 holds the value of the customer4 edge.
     * @type {Array<EntCustomer>}
     * @memberof EntTitleEdges
     */
    customer4?: Array<EntCustomer>;
}

export function EntTitleEdgesFromJSON(json: any): EntTitleEdges {
    return EntTitleEdgesFromJSONTyped(json, false);
}

export function EntTitleEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTitleEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer4': !exists(json, 'customer4') ? undefined : ((json['customer4'] as Array<any>).map(EntCustomerFromJSON)),
    };
}

export function EntTitleEdgesToJSON(value?: EntTitleEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer4': value.customer4 === undefined ? undefined : ((value.customer4 as Array<any>).map(EntCustomerToJSON)),
    };
}


