// Code generated by entc, DO NOT EDIT.

package gender

const (
	// Label holds the string label denoting the gender type in the database.
	Label = "gender"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGENDER holds the string denoting the gender field in the database.
	FieldGENDER = "gender"

	// EdgeCustomer2 holds the string denoting the customer2 edge name in mutations.
	EdgeCustomer2 = "customer2"

	// Table holds the table name of the gender in the database.
	Table = "genders"
	// Customer2Table is the table the holds the customer2 relation/edge.
	Customer2Table = "customers"
	// Customer2InverseTable is the table name for the Customer entity.
	// It exists in this package in order to avoid circular dependency with the "customer" package.
	Customer2InverseTable = "customers"
	// Customer2Column is the table column denoting the customer2 relation/edge.
	Customer2Column = "gender"
)

// Columns holds all SQL columns for gender fields.
var Columns = []string{
	FieldID,
	FieldGENDER,
}

var (
	// GENDERValidator is a validator for the "GENDER" field. It is called by the builders before save.
	GENDERValidator func(string) error
)
