/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntProblem,
    EntProblemFromJSON,
    EntProblemFromJSONTyped,
    EntProblemToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCustomerEdges
 */
export interface EntCustomerEdges {
    /**
     * Problem holds the value of the Problem edge.
     * @type {Array<EntProblem>}
     * @memberof EntCustomerEdges
     */
    problem?: Array<EntProblem>;
}

export function EntCustomerEdgesFromJSON(json: any): EntCustomerEdges {
    return EntCustomerEdgesFromJSONTyped(json, false);
}

export function EntCustomerEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCustomerEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'problem': !exists(json, 'problem') ? undefined : ((json['problem'] as Array<any>).map(EntProblemFromJSON)),
    };
}

export function EntCustomerEdgesToJSON(value?: EntCustomerEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'problem': value.problem === undefined ? undefined : ((value.problem as Array<any>).map(EntProblemToJSON)),
    };
}


