/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntProblemEdges,
    EntProblemEdgesFromJSON,
    EntProblemEdgesFromJSONTyped,
    EntProblemEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntProblem
 */
export interface EntProblem {
    /**
     * PROBLEMDETAIL holds the value of the "PROBLEMDETAIL" field.
     * @type {string}
     * @memberof EntProblem
     */
    pROBLEMDETAIL?: string;
    /**
     * 
     * @type {EntProblemEdges}
     * @memberof EntProblem
     */
    edges?: EntProblemEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntProblem
     */
    id?: number;
}

export function EntProblemFromJSON(json: any): EntProblem {
    return EntProblemFromJSONTyped(json, false);
}

export function EntProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntProblem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pROBLEMDETAIL': !exists(json, 'PROBLEMDETAIL') ? undefined : json['PROBLEMDETAIL'],
        'edges': !exists(json, 'edges') ? undefined : EntProblemEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntProblemToJSON(value?: EntProblem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PROBLEMDETAIL': value.pROBLEMDETAIL,
        'edges': EntProblemEdgesToJSON(value.edges),
        'id': value.id,
    };
}


