// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/PBank/app/ent/predicate"
	"github.com/PBank/app/ent/promotion"
	"github.com/PBank/app/ent/room"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PromotionUpdate is the builder for updating Promotion entities.
type PromotionUpdate struct {
	config
	hooks      []Hook
	mutation   *PromotionMutation
	predicates []predicate.Promotion
}

// Where adds a new predicate for the builder.
func (pu *PromotionUpdate) Where(ps ...predicate.Promotion) *PromotionUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetPROMOTIONDETAIL sets the PROMOTIONDETAIL field.
func (pu *PromotionUpdate) SetPROMOTIONDETAIL(s string) *PromotionUpdate {
	pu.mutation.SetPROMOTIONDETAIL(s)
	return pu
}

// AddRoom2IDs adds the Room2 edge to Room by ids.
func (pu *PromotionUpdate) AddRoom2IDs(ids ...int) *PromotionUpdate {
	pu.mutation.AddRoom2IDs(ids...)
	return pu
}

// AddRoom2 adds the Room2 edges to Room.
func (pu *PromotionUpdate) AddRoom2(r ...*Room) *PromotionUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pu.AddRoom2IDs(ids...)
}

// Mutation returns the PromotionMutation object of the builder.
func (pu *PromotionUpdate) Mutation() *PromotionMutation {
	return pu.mutation
}

// RemoveRoom2IDs removes the Room2 edge to Room by ids.
func (pu *PromotionUpdate) RemoveRoom2IDs(ids ...int) *PromotionUpdate {
	pu.mutation.RemoveRoom2IDs(ids...)
	return pu
}

// RemoveRoom2 removes Room2 edges to Room.
func (pu *PromotionUpdate) RemoveRoom2(r ...*Room) *PromotionUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pu.RemoveRoom2IDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PromotionUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PromotionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PromotionUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PromotionUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PromotionUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PromotionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   promotion.Table,
			Columns: promotion.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: promotion.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.PROMOTIONDETAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: promotion.FieldPROMOTIONDETAIL,
		})
	}
	if nodes := pu.mutation.RemovedRoom2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promotion.Room2Table,
			Columns: []string{promotion.Room2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.Room2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promotion.Room2Table,
			Columns: []string{promotion.Room2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotion.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PromotionUpdateOne is the builder for updating a single Promotion entity.
type PromotionUpdateOne struct {
	config
	hooks    []Hook
	mutation *PromotionMutation
}

// SetPROMOTIONDETAIL sets the PROMOTIONDETAIL field.
func (puo *PromotionUpdateOne) SetPROMOTIONDETAIL(s string) *PromotionUpdateOne {
	puo.mutation.SetPROMOTIONDETAIL(s)
	return puo
}

// AddRoom2IDs adds the Room2 edge to Room by ids.
func (puo *PromotionUpdateOne) AddRoom2IDs(ids ...int) *PromotionUpdateOne {
	puo.mutation.AddRoom2IDs(ids...)
	return puo
}

// AddRoom2 adds the Room2 edges to Room.
func (puo *PromotionUpdateOne) AddRoom2(r ...*Room) *PromotionUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return puo.AddRoom2IDs(ids...)
}

// Mutation returns the PromotionMutation object of the builder.
func (puo *PromotionUpdateOne) Mutation() *PromotionMutation {
	return puo.mutation
}

// RemoveRoom2IDs removes the Room2 edge to Room by ids.
func (puo *PromotionUpdateOne) RemoveRoom2IDs(ids ...int) *PromotionUpdateOne {
	puo.mutation.RemoveRoom2IDs(ids...)
	return puo
}

// RemoveRoom2 removes Room2 edges to Room.
func (puo *PromotionUpdateOne) RemoveRoom2(r ...*Room) *PromotionUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return puo.RemoveRoom2IDs(ids...)
}

// Save executes the query and returns the updated entity.
func (puo *PromotionUpdateOne) Save(ctx context.Context) (*Promotion, error) {

	var (
		err  error
		node *Promotion
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PromotionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PromotionUpdateOne) SaveX(ctx context.Context) *Promotion {
	pr, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return pr
}

// Exec executes the query on the entity.
func (puo *PromotionUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PromotionUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PromotionUpdateOne) sqlSave(ctx context.Context) (pr *Promotion, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   promotion.Table,
			Columns: promotion.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: promotion.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Promotion.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.PROMOTIONDETAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: promotion.FieldPROMOTIONDETAIL,
		})
	}
	if nodes := puo.mutation.RemovedRoom2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promotion.Room2Table,
			Columns: []string{promotion.Room2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.Room2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promotion.Room2Table,
			Columns: []string{promotion.Room2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	pr = &Promotion{config: puo.config}
	_spec.Assign = pr.assignValues
	_spec.ScanValues = pr.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotion.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return pr, nil
}
