// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/PBank/app/ent/promotion"
	"github.com/PBank/app/ent/room"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PromotionCreate is the builder for creating a Promotion entity.
type PromotionCreate struct {
	config
	mutation *PromotionMutation
	hooks    []Hook
}

// SetPROMOTIONDETAIL sets the PROMOTIONDETAIL field.
func (pc *PromotionCreate) SetPROMOTIONDETAIL(s string) *PromotionCreate {
	pc.mutation.SetPROMOTIONDETAIL(s)
	return pc
}

// AddRoom2IDs adds the Room2 edge to Room by ids.
func (pc *PromotionCreate) AddRoom2IDs(ids ...int) *PromotionCreate {
	pc.mutation.AddRoom2IDs(ids...)
	return pc
}

// AddRoom2 adds the Room2 edges to Room.
func (pc *PromotionCreate) AddRoom2(r ...*Room) *PromotionCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pc.AddRoom2IDs(ids...)
}

// Mutation returns the PromotionMutation object of the builder.
func (pc *PromotionCreate) Mutation() *PromotionMutation {
	return pc.mutation
}

// Save creates the Promotion in the database.
func (pc *PromotionCreate) Save(ctx context.Context) (*Promotion, error) {
	if _, ok := pc.mutation.PROMOTIONDETAIL(); !ok {
		return nil, &ValidationError{Name: "PROMOTIONDETAIL", err: errors.New("ent: missing required field \"PROMOTIONDETAIL\"")}
	}
	var (
		err  error
		node *Promotion
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PromotionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PromotionCreate) SaveX(ctx context.Context) *Promotion {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PromotionCreate) sqlSave(ctx context.Context) (*Promotion, error) {
	pr, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pr.ID = int(id)
	return pr, nil
}

func (pc *PromotionCreate) createSpec() (*Promotion, *sqlgraph.CreateSpec) {
	var (
		pr    = &Promotion{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: promotion.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: promotion.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.PROMOTIONDETAIL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: promotion.FieldPROMOTIONDETAIL,
		})
		pr.PROMOTIONDETAIL = value
	}
	if nodes := pc.mutation.Room2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promotion.Room2Table,
			Columns: []string{promotion.Room2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pr, _spec
}
