// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/PBank/app/ent/roomstate"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Roomstate is the model entity for the Roomstate schema.
type Roomstate struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ROOMSTATE holds the value of the "ROOMSTATE" field.
	ROOMSTATE string `json:"ROOMSTATE,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoomstateQuery when eager-loading is set.
	Edges RoomstateEdges `json:"edges"`
}

// RoomstateEdges holds the relations/edges for other nodes in the graph.
type RoomstateEdges struct {
	// Room3 holds the value of the Room3 edge.
	Room3 []*Room
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// Room3OrErr returns the Room3 value or an error if the edge
// was not loaded in eager-loading.
func (e RoomstateEdges) Room3OrErr() ([]*Room, error) {
	if e.loadedTypes[0] {
		return e.Room3, nil
	}
	return nil, &NotLoadedError{edge: "Room3"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Roomstate) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // ROOMSTATE
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Roomstate fields.
func (r *Roomstate) assignValues(values ...interface{}) error {
	if m, n := len(values), len(roomstate.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	r.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field ROOMSTATE", values[0])
	} else if value.Valid {
		r.ROOMSTATE = value.String
	}
	return nil
}

// QueryRoom3 queries the Room3 edge of the Roomstate.
func (r *Roomstate) QueryRoom3() *RoomQuery {
	return (&RoomstateClient{config: r.config}).QueryRoom3(r)
}

// Update returns a builder for updating this Roomstate.
// Note that, you need to call Roomstate.Unwrap() before calling this method, if this Roomstate
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Roomstate) Update() *RoomstateUpdateOne {
	return (&RoomstateClient{config: r.config}).UpdateOne(r)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (r *Roomstate) Unwrap() *Roomstate {
	tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Roomstate is not a transactional entity")
	}
	r.config.driver = tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Roomstate) String() string {
	var builder strings.Builder
	builder.WriteString("Roomstate(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteString(", ROOMSTATE=")
	builder.WriteString(r.ROOMSTATE)
	builder.WriteByte(')')
	return builder.String()
}

// Roomstates is a parsable slice of Roomstate.
type Roomstates []*Roomstate

func (r Roomstates) config(cfg config) {
	for _i := range r {
		r[_i].config = cfg
	}
}
