// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/PBank/app/ent/predicate"
	"github.com/PBank/app/ent/room"
	"github.com/PBank/app/ent/roomstate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomstateUpdate is the builder for updating Roomstate entities.
type RoomstateUpdate struct {
	config
	hooks      []Hook
	mutation   *RoomstateMutation
	predicates []predicate.Roomstate
}

// Where adds a new predicate for the builder.
func (ru *RoomstateUpdate) Where(ps ...predicate.Roomstate) *RoomstateUpdate {
	ru.predicates = append(ru.predicates, ps...)
	return ru
}

// SetROOMSTATE sets the ROOMSTATE field.
func (ru *RoomstateUpdate) SetROOMSTATE(s string) *RoomstateUpdate {
	ru.mutation.SetROOMSTATE(s)
	return ru
}

// AddRoom3IDs adds the Room3 edge to Room by ids.
func (ru *RoomstateUpdate) AddRoom3IDs(ids ...int) *RoomstateUpdate {
	ru.mutation.AddRoom3IDs(ids...)
	return ru
}

// AddRoom3 adds the Room3 edges to Room.
func (ru *RoomstateUpdate) AddRoom3(r ...*Room) *RoomstateUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddRoom3IDs(ids...)
}

// Mutation returns the RoomstateMutation object of the builder.
func (ru *RoomstateUpdate) Mutation() *RoomstateMutation {
	return ru.mutation
}

// RemoveRoom3IDs removes the Room3 edge to Room by ids.
func (ru *RoomstateUpdate) RemoveRoom3IDs(ids ...int) *RoomstateUpdate {
	ru.mutation.RemoveRoom3IDs(ids...)
	return ru
}

// RemoveRoom3 removes Room3 edges to Room.
func (ru *RoomstateUpdate) RemoveRoom3(r ...*Room) *RoomstateUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemoveRoom3IDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ru *RoomstateUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := ru.mutation.ROOMSTATE(); ok {
		if err := roomstate.ROOMSTATEValidator(v); err != nil {
			return 0, &ValidationError{Name: "ROOMSTATE", err: fmt.Errorf("ent: validator failed for field \"ROOMSTATE\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomstateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoomstateUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoomstateUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoomstateUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RoomstateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roomstate.Table,
			Columns: roomstate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomstate.FieldID,
			},
		},
	}
	if ps := ru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.ROOMSTATE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomstate.FieldROOMSTATE,
		})
	}
	if nodes := ru.mutation.RemovedRoom3IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomstate.Room3Table,
			Columns: []string{roomstate.Room3Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.Room3IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomstate.Room3Table,
			Columns: []string{roomstate.Room3Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roomstate.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoomstateUpdateOne is the builder for updating a single Roomstate entity.
type RoomstateUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoomstateMutation
}

// SetROOMSTATE sets the ROOMSTATE field.
func (ruo *RoomstateUpdateOne) SetROOMSTATE(s string) *RoomstateUpdateOne {
	ruo.mutation.SetROOMSTATE(s)
	return ruo
}

// AddRoom3IDs adds the Room3 edge to Room by ids.
func (ruo *RoomstateUpdateOne) AddRoom3IDs(ids ...int) *RoomstateUpdateOne {
	ruo.mutation.AddRoom3IDs(ids...)
	return ruo
}

// AddRoom3 adds the Room3 edges to Room.
func (ruo *RoomstateUpdateOne) AddRoom3(r ...*Room) *RoomstateUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddRoom3IDs(ids...)
}

// Mutation returns the RoomstateMutation object of the builder.
func (ruo *RoomstateUpdateOne) Mutation() *RoomstateMutation {
	return ruo.mutation
}

// RemoveRoom3IDs removes the Room3 edge to Room by ids.
func (ruo *RoomstateUpdateOne) RemoveRoom3IDs(ids ...int) *RoomstateUpdateOne {
	ruo.mutation.RemoveRoom3IDs(ids...)
	return ruo
}

// RemoveRoom3 removes Room3 edges to Room.
func (ruo *RoomstateUpdateOne) RemoveRoom3(r ...*Room) *RoomstateUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemoveRoom3IDs(ids...)
}

// Save executes the query and returns the updated entity.
func (ruo *RoomstateUpdateOne) Save(ctx context.Context) (*Roomstate, error) {
	if v, ok := ruo.mutation.ROOMSTATE(); ok {
		if err := roomstate.ROOMSTATEValidator(v); err != nil {
			return nil, &ValidationError{Name: "ROOMSTATE", err: fmt.Errorf("ent: validator failed for field \"ROOMSTATE\": %w", err)}
		}
	}

	var (
		err  error
		node *Roomstate
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomstateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoomstateUpdateOne) SaveX(ctx context.Context) *Roomstate {
	r, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return r
}

// Exec executes the query on the entity.
func (ruo *RoomstateUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoomstateUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RoomstateUpdateOne) sqlSave(ctx context.Context) (r *Roomstate, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roomstate.Table,
			Columns: roomstate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomstate.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Roomstate.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ruo.mutation.ROOMSTATE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomstate.FieldROOMSTATE,
		})
	}
	if nodes := ruo.mutation.RemovedRoom3IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomstate.Room3Table,
			Columns: []string{roomstate.Room3Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.Room3IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomstate.Room3Table,
			Columns: []string{roomstate.Room3Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	r = &Roomstate{config: ruo.config}
	_spec.Assign = r.assignValues
	_spec.ScanValues = r.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roomstate.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return r, nil
}
