// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/PBank/app/ent/predicate"
	"github.com/PBank/app/ent/promotion"
	"github.com/PBank/app/ent/room"
	"github.com/PBank/app/ent/roomstate"
	"github.com/PBank/app/ent/roomtype"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomUpdate is the builder for updating Room entities.
type RoomUpdate struct {
	config
	hooks      []Hook
	mutation   *RoomMutation
	predicates []predicate.Room
}

// Where adds a new predicate for the builder.
func (ru *RoomUpdate) Where(ps ...predicate.Room) *RoomUpdate {
	ru.predicates = append(ru.predicates, ps...)
	return ru
}

// SetROOMNUMBER sets the ROOMNUMBER field.
func (ru *RoomUpdate) SetROOMNUMBER(s string) *RoomUpdate {
	ru.mutation.SetROOMNUMBER(s)
	return ru
}

// SetRoomtypeID sets the Roomtype edge to Roomtype by id.
func (ru *RoomUpdate) SetRoomtypeID(id int) *RoomUpdate {
	ru.mutation.SetRoomtypeID(id)
	return ru
}

// SetNillableRoomtypeID sets the Roomtype edge to Roomtype by id if the given value is not nil.
func (ru *RoomUpdate) SetNillableRoomtypeID(id *int) *RoomUpdate {
	if id != nil {
		ru = ru.SetRoomtypeID(*id)
	}
	return ru
}

// SetRoomtype sets the Roomtype edge to Roomtype.
func (ru *RoomUpdate) SetRoomtype(r *Roomtype) *RoomUpdate {
	return ru.SetRoomtypeID(r.ID)
}

// SetPromotionID sets the Promotion edge to Promotion by id.
func (ru *RoomUpdate) SetPromotionID(id int) *RoomUpdate {
	ru.mutation.SetPromotionID(id)
	return ru
}

// SetNillablePromotionID sets the Promotion edge to Promotion by id if the given value is not nil.
func (ru *RoomUpdate) SetNillablePromotionID(id *int) *RoomUpdate {
	if id != nil {
		ru = ru.SetPromotionID(*id)
	}
	return ru
}

// SetPromotion sets the Promotion edge to Promotion.
func (ru *RoomUpdate) SetPromotion(p *Promotion) *RoomUpdate {
	return ru.SetPromotionID(p.ID)
}

// SetRoomstateID sets the roomstate edge to Roomstate by id.
func (ru *RoomUpdate) SetRoomstateID(id int) *RoomUpdate {
	ru.mutation.SetRoomstateID(id)
	return ru
}

// SetNillableRoomstateID sets the roomstate edge to Roomstate by id if the given value is not nil.
func (ru *RoomUpdate) SetNillableRoomstateID(id *int) *RoomUpdate {
	if id != nil {
		ru = ru.SetRoomstateID(*id)
	}
	return ru
}

// SetRoomstate sets the roomstate edge to Roomstate.
func (ru *RoomUpdate) SetRoomstate(r *Roomstate) *RoomUpdate {
	return ru.SetRoomstateID(r.ID)
}

// Mutation returns the RoomMutation object of the builder.
func (ru *RoomUpdate) Mutation() *RoomMutation {
	return ru.mutation
}

// ClearRoomtype clears the Roomtype edge to Roomtype.
func (ru *RoomUpdate) ClearRoomtype() *RoomUpdate {
	ru.mutation.ClearRoomtype()
	return ru
}

// ClearPromotion clears the Promotion edge to Promotion.
func (ru *RoomUpdate) ClearPromotion() *RoomUpdate {
	ru.mutation.ClearPromotion()
	return ru
}

// ClearRoomstate clears the roomstate edge to Roomstate.
func (ru *RoomUpdate) ClearRoomstate() *RoomUpdate {
	ru.mutation.ClearRoomstate()
	return ru
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ru *RoomUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoomUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoomUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoomUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RoomUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   room.Table,
			Columns: room.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: room.FieldID,
			},
		},
	}
	if ps := ru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.ROOMNUMBER(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: room.FieldROOMNUMBER,
		})
	}
	if ru.mutation.RoomtypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomtypeTable,
			Columns: []string{room.RoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoomtypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomtypeTable,
			Columns: []string{room.RoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.PromotionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.PromotionTable,
			Columns: []string{room.PromotionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: promotion.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.PromotionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.PromotionTable,
			Columns: []string{room.PromotionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: promotion.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.RoomstateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomstateTable,
			Columns: []string{room.RoomstateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstate.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoomstateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomstateTable,
			Columns: []string{room.RoomstateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstate.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoomUpdateOne is the builder for updating a single Room entity.
type RoomUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoomMutation
}

// SetROOMNUMBER sets the ROOMNUMBER field.
func (ruo *RoomUpdateOne) SetROOMNUMBER(s string) *RoomUpdateOne {
	ruo.mutation.SetROOMNUMBER(s)
	return ruo
}

// SetRoomtypeID sets the Roomtype edge to Roomtype by id.
func (ruo *RoomUpdateOne) SetRoomtypeID(id int) *RoomUpdateOne {
	ruo.mutation.SetRoomtypeID(id)
	return ruo
}

// SetNillableRoomtypeID sets the Roomtype edge to Roomtype by id if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableRoomtypeID(id *int) *RoomUpdateOne {
	if id != nil {
		ruo = ruo.SetRoomtypeID(*id)
	}
	return ruo
}

// SetRoomtype sets the Roomtype edge to Roomtype.
func (ruo *RoomUpdateOne) SetRoomtype(r *Roomtype) *RoomUpdateOne {
	return ruo.SetRoomtypeID(r.ID)
}

// SetPromotionID sets the Promotion edge to Promotion by id.
func (ruo *RoomUpdateOne) SetPromotionID(id int) *RoomUpdateOne {
	ruo.mutation.SetPromotionID(id)
	return ruo
}

// SetNillablePromotionID sets the Promotion edge to Promotion by id if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillablePromotionID(id *int) *RoomUpdateOne {
	if id != nil {
		ruo = ruo.SetPromotionID(*id)
	}
	return ruo
}

// SetPromotion sets the Promotion edge to Promotion.
func (ruo *RoomUpdateOne) SetPromotion(p *Promotion) *RoomUpdateOne {
	return ruo.SetPromotionID(p.ID)
}

// SetRoomstateID sets the roomstate edge to Roomstate by id.
func (ruo *RoomUpdateOne) SetRoomstateID(id int) *RoomUpdateOne {
	ruo.mutation.SetRoomstateID(id)
	return ruo
}

// SetNillableRoomstateID sets the roomstate edge to Roomstate by id if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableRoomstateID(id *int) *RoomUpdateOne {
	if id != nil {
		ruo = ruo.SetRoomstateID(*id)
	}
	return ruo
}

// SetRoomstate sets the roomstate edge to Roomstate.
func (ruo *RoomUpdateOne) SetRoomstate(r *Roomstate) *RoomUpdateOne {
	return ruo.SetRoomstateID(r.ID)
}

// Mutation returns the RoomMutation object of the builder.
func (ruo *RoomUpdateOne) Mutation() *RoomMutation {
	return ruo.mutation
}

// ClearRoomtype clears the Roomtype edge to Roomtype.
func (ruo *RoomUpdateOne) ClearRoomtype() *RoomUpdateOne {
	ruo.mutation.ClearRoomtype()
	return ruo
}

// ClearPromotion clears the Promotion edge to Promotion.
func (ruo *RoomUpdateOne) ClearPromotion() *RoomUpdateOne {
	ruo.mutation.ClearPromotion()
	return ruo
}

// ClearRoomstate clears the roomstate edge to Roomstate.
func (ruo *RoomUpdateOne) ClearRoomstate() *RoomUpdateOne {
	ruo.mutation.ClearRoomstate()
	return ruo
}

// Save executes the query and returns the updated entity.
func (ruo *RoomUpdateOne) Save(ctx context.Context) (*Room, error) {

	var (
		err  error
		node *Room
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoomUpdateOne) SaveX(ctx context.Context) *Room {
	r, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return r
}

// Exec executes the query on the entity.
func (ruo *RoomUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoomUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RoomUpdateOne) sqlSave(ctx context.Context) (r *Room, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   room.Table,
			Columns: room.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: room.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Room.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ruo.mutation.ROOMNUMBER(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: room.FieldROOMNUMBER,
		})
	}
	if ruo.mutation.RoomtypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomtypeTable,
			Columns: []string{room.RoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoomtypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomtypeTable,
			Columns: []string{room.RoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.PromotionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.PromotionTable,
			Columns: []string{room.PromotionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: promotion.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.PromotionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.PromotionTable,
			Columns: []string{room.PromotionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: promotion.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.RoomstateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomstateTable,
			Columns: []string{room.RoomstateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstate.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoomstateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomstateTable,
			Columns: []string{room.RoomstateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstate.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	r = &Room{config: ruo.config}
	_spec.Assign = r.assignValues
	_spec.ScanValues = r.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return r, nil
}
