/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoom,
    EntRoomFromJSON,
    EntRoomFromJSONTyped,
    EntRoomToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomstateEdges
 */
export interface EntRoomstateEdges {
    /**
     * Room3 holds the value of the Room3 edge.
     * @type {Array<EntRoom>}
     * @memberof EntRoomstateEdges
     */
    room3?: Array<EntRoom>;
}

export function EntRoomstateEdgesFromJSON(json: any): EntRoomstateEdges {
    return EntRoomstateEdgesFromJSONTyped(json, false);
}

export function EntRoomstateEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomstateEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'room3': !exists(json, 'room3') ? undefined : ((json['room3'] as Array<any>).map(EntRoomFromJSON)),
    };
}

export function EntRoomstateEdgesToJSON(value?: EntRoomstateEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'room3': value.room3 === undefined ? undefined : ((value.room3 as Array<any>).map(EntRoomToJSON)),
    };
}


